function(add_example name)
    add_executable(${name} ${name}.cpp)
    target_link_libraries(${name} PRIVATE MLlib)
endfunction()

add_example(markowitz)
add_example(markowitz_ad)
add_example(black_scholes)
add_example(black_scholes_cfd)
add_example(black_scholes_multistart)
add_example(black_scholes_newton)
add_example(black_scholes_newton_multistart)